# Generated by Django 2.1 on 2018-08-02 14:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(29)])),
                ('study_time', models.PositiveIntegerField(choices=[(1, '> 2hours'), (2, '2 to 5 hours'), (3, '5 to 10 hours'), (4, '< 10 hours')])),
                ('activities', models.BooleanField()),
                ('higher_edu', models.BooleanField()),
                ('freetime_level', models.PositiveIntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'moderate'), (4, 'high'), (5, 'very high')])),
                ('outing_level', models.PositiveIntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'moderate'), (4, 'high'), (5, 'very high')])),
                ('weekend_alcohol_level', models.PositiveIntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'moderate'), (4, 'high'), (5, 'very high')])),
                ('health_status', models.PositiveIntegerField(choices=[(1, 'very low'), (2, 'low'), (3, 'moderate'), (4, 'high'), (5, 'very high')])),
                ('absent_weeks', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(6)])),
                ('gp1', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0)])),
                ('gp2', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0)])),
                ('predicted_class', models.CharField(max_length=10)),
                ('recorded_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
