# Generated by Django 2.1 on 2018-08-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentperformance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='activities',
            field=models.BooleanField(help_text='Are you involved in Extra-curricular activities'),
        ),
    ]
