# Generated by Django 2.1 on 2018-08-02 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentperformance', '0003_auto_20180802_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='activities',
            field=models.BooleanField(verbose_name='Are you involved in Extra-curricular activities'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='gp1',
            field=models.DecimalField(decimal_places=2, help_text='First Semester GP', max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='gp2',
            field=models.DecimalField(decimal_places=2, help_text='Second Semester GP', max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
    ]
