# Generated by Django 2.1 on 2018-08-02 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentperformance', '0004_auto_20180802_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='age',
            field=models.PositiveIntegerField(help_text='You must be btw 16-29', validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(29)]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='freetime_level',
            field=models.PositiveIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='gp1',
            field=models.DecimalField(decimal_places=2, help_text='First Semester GP range(0-4.00)', max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='gp2',
            field=models.DecimalField(decimal_places=2, help_text='Second Semester GP range(0-4.00)', max_digits=3, validators=[django.core.validators.MaxValueValidator(4.0)]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='health_status',
            field=models.PositiveIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='outing_level',
            field=models.PositiveIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='study_time',
            field=models.PositiveIntegerField(choices=[(1, '> 2 hours'), (2, '2 to 5 hours'), (3, '5 to 10 hours'), (4, '< 10 hours')]),
        ),
        migrations.AlterField(
            model_name='performance',
            name='weekend_alcohol_level',
            field=models.PositiveIntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Moderate'), (4, 'High'), (5, 'Very High')]),
        ),
    ]
