# Generated by Django 2.1 on 2018-08-02 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentperformance', '0005_auto_20180802_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='absent_weeks',
            field=models.PositiveIntegerField(help_text='Must not be more than 6 weeks', validators=[django.core.validators.MaxValueValidator(6)]),
        ),
    ]
