# Generated by Django 2.1 on 2018-08-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentperformance', '0006_auto_20180802_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='activities',
            field=models.BooleanField(default=False, verbose_name='Are you involved in Extra-curricular activities'),
        ),
        migrations.AlterField(
            model_name='performance',
            name='higher_edu',
            field=models.BooleanField(default=False, verbose_name='Do you intend to pursue an higher education?'),
        ),
    ]
